ALTER TABLE apps ADD COLUMN mail_collab BOOLEAN DEFAULT FALSE; 
ALTER TABLE apps ADD COLUMN mail_viewers BOOLEAN DEFAULT FALSE; 


CREATE TABLE subscription (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  app INTEGER NOT NULL,
  principal INTEGER NOT NULL,
  include BOOLEAN NOT NULL);
